import { money } from "./commerce.ts";
export function escapeHtml(value: unknown) {
  return String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
}
function url(base: string, path: string) { return escapeHtml(new URL(path, base).href); }
function button(base: string, path: string, label: string) {
  return `<table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#283c30" style="border-radius:4px;text-align:center;mso-padding-alt:16px 26px;"><a href="${url(base,path)}" style="display:inline-block;padding:16px 26px;font:600 14px Arial,sans-serif;color:#ffffff;text-decoration:none;">${label} &nbsp; &rarr;</a></td></tr></table>`;
}
function shell(base: string, preheader: string, content: string) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Okirika</title><style>@media only screen and (max-width:600px){.email-pad{padding-left:24px!important;padding-right:24px!important}.email-heading{font-size:32px!important}.email-outer{padding:12px 0!important}}</style></head><body style="margin:0;padding:0;background:#eeeee5;color:#283c30;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">${escapeHtml(preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" bgcolor="#eeeee5"><tr><td class="email-outer" align="center" style="padding:32px 12px;"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#f8f6ef;"><tr><td bgcolor="#283c30" align="center" style="padding:13px;color:#f8f6ef;font:10px Arial,sans-serif;letter-spacing:2px;">OBJECTS FOR EVERYDAY LIVING</td></tr><tr><td class="email-pad" style="padding:32px 44px 26px;"><a href="${url(base,'/')}" style="text-decoration:none;color:#283c30;"><img src="${url(base,'/email/okirika-logo.png')}" alt="okirika®" width="180" height="53" style="display:block;border:0;width:180px;height:53px;color:#283c30;font:bold 34px Georgia,serif;"></a></td></tr>${content}<tr><td class="email-pad" style="padding:24px 44px;border-top:1px solid #dfe2d4;"><p style="margin:0 0 9px;font:10px Arial,sans-serif;font-weight:bold;letter-spacing:1px;">A NOTE ABOUT TEST MODE</p><p style="margin:0;font:12px/1.7 Arial,sans-serif;color:#687360;">The shop is currently in test mode. No real charges or shipments are made.</p></td></tr><tr><td class="email-pad" bgcolor="#283c30" style="padding:30px 44px;color:#f8f6ef;"><p style="font:24px/1.3 Georgia,serif;margin:0 0 20px;">A home is made of little things.</p><p style="font:12px/1.8 Arial,sans-serif;margin:0 0 18px;"><a href="${url(base,'/#collection')}" style="color:#f8f6ef;">The collection</a> &nbsp; &middot; &nbsp; <a href="${url(base,'/orders')}" style="color:#f8f6ef;">Your orders</a> &nbsp; &middot; &nbsp; <a href="${url(base,'/help')}" style="color:#f8f6ef;">Shopping help</a></p><p style="font:10px/1.8 Arial,sans-serif;color:#c5cebd;margin:0;">Sent for your Okirika account or order.<br>&copy; ${new Date().getFullYear()} Okirika &middot; Nigeria</p></td></tr></table></td></tr></table></body></html>`;
}
const p = 'font:14px/1.8 Arial,sans-serif;color:#596651;margin:0 0 20px;';
const label = 'font:10px/1.5 Arial,sans-serif;letter-spacing:2px;font-weight:bold;margin:0 0 16px;color:#687360;';
const heading = 'font:38px/1.15 Georgia,serif;font-weight:normal;letter-spacing:-1px;margin:0 0 22px;color:#283c30;';
export function welcomeHtml(name: string, base: string) {
  return shell(base, 'Welcome to Okirika. Your account is ready — make yourself at home.', `<tr><td><img src="${url(base,'/home-edit.png')}" alt="Thoughtfully chosen pieces for your home" width="600" style="display:block;width:100%;max-width:600px;height:auto;border:0;"></td></tr><tr><td class="email-pad" style="padding:36px 44px 40px;"><p style="${label}">YOUR ACCOUNT IS READY</p><h1 class="email-heading" style="${heading}">Make yourself<br>at home.</h1><p style="${p}">Hello ${escapeHtml(name)},</p><p style="${p}">Welcome to Okirika. We’re glad you’re here. Discover thoughtful pieces and everyday comforts to make your space feel like you.</p><p style="${p}">Your account is ready. Save your shopping bag, enjoy a simple checkout, and keep all your orders in one place.</p>${button(base,'/#collection','Explore the collection')}<p style="${p}margin-top:28px;margin-bottom:0;">With care,<br><strong style="color:#283c30;">The Okirika team</strong></p></td></tr>`);
}
export type ReceiptEmail = { reference: string; delivery: {name: string;address: string;city: string;state: string}; items: {name: string;quantity: number;price: number}[]; subtotal: number; shipping: number; total: number };
export function receiptHtml(order: ReceiptEmail, base: string) {
  const rows = order.items.map(item => `<tr><td style="padding:16px 0;border-bottom:1px solid #dfe2d4;font:14px/1.5 Arial,sans-serif;color:#283c30;">${escapeHtml(item.name)}<br><span style="font-size:11px;color:#687360;">Quantity: ${escapeHtml(item.quantity)}</span></td><td align="right" style="padding:16px 0;border-bottom:1px solid #dfe2d4;font:13px Arial,sans-serif;white-space:nowrap;">${escapeHtml(money(item.price*item.quantity))}</td></tr>`).join('');
  const total = (name: string, amount: number, bold=false) => `<tr><td style="padding-top:16px;font:${bold?'bold 17':'13'}px Arial,sans-serif;">${name}</td><td align="right" style="padding-top:16px;font:${bold?'bold 17':'13'}px Arial,sans-serif;white-space:nowrap;">${escapeHtml(money(amount))}</td></tr>`;
  return shell(base,'Thank you for your patronage! Your Okirika payment is confirmed.',`<tr><td class="email-pad" style="padding:12px 44px 36px;"><p style="${label}">PAYMENT CONFIRMED</p><h1 class="email-heading" style="${heading}">Thank you for<br>your patronage!</h1><p style="${p}">Hello ${escapeHtml(order.delivery.name)}, your test payment has been verified and your order is confirmed. Thank you for choosing Okirika.</p><p style="font:10px/1.8 Arial,sans-serif;color:#687360;margin:0 0 20px;overflow-wrap:anywhere;word-break:break-word;">ORDER REFERENCE<br>${escapeHtml(order.reference)}</p><table width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #dfe2d4;"><caption style="text-align:left;font:22px Georgia,serif;padding-bottom:14px;">Your good things</caption><thead><tr><th align="left" style="padding-top:14px;font:10px Arial,sans-serif;">ITEM</th><th align="right" style="padding-top:14px;font:10px Arial,sans-serif;">AMOUNT</th></tr></thead><tbody>${rows}${total('Subtotal',order.subtotal)}${total('Delivery',order.shipping)}${total('Total paid',order.total,true)}</tbody></table><p style="font:10px Arial,sans-serif;color:#687360;margin:12px 0 28px;">All amounts in Nigerian naira.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" bgcolor="#eeeee4"><tr><td style="padding:20px;"><p style="${label}margin-bottom:10px;">DELIVERY DETAILS</p><p style="${p}margin:0;">${escapeHtml(order.delivery.name)}<br>${escapeHtml(order.delivery.address)}<br>${escapeHtml(order.delivery.city)}, ${escapeHtml(order.delivery.state)}<br>Nigeria</p></td></tr></table><p style="${p}margin-top:24px;">You can find this order and its payment status in your account at any time.</p>${button(base,'/orders','View your order')}<p style="${p}margin-top:28px;margin-bottom:0;">With care,<br><strong style="color:#283c30;">The Okirika team</strong></p></td></tr>`);
}
